name: Check all install extras

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8","3.9","3.10","3.11"] # want to add 3.12 soon
        os: [ubuntu-latest, windows-latest, macos-latest]
        extras:
          - ipympl
          - plotly
          - bokeh
          - k3d
          - qt
          - myavi
          - test

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install using flags
        run: |
          pip install .[${{ matrix.extras }}]

      - name: Test with pytest
        run: pytest
